#!/bin/bash
if [ $# -eq 0 ]; then
  echo "No argument provided"
fi

if [ $1 = 1 ]; then
./ex7_VoIP_full -r 0 -u Cmdenv -c TwentyFiveVoIPsBestCaseISDN -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 1 -u Cmdenv -c TwentyFiveVoIPsBestCaseISDN -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 2 -u Cmdenv -c TwentyFiveVoIPsBestCaseISDN -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 3 -u Cmdenv -c TwentyFiveVoIPsBestCaseISDN -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
fi
if [ $1 = 2 ]; then
./ex7_VoIP_full -r 0 -u Cmdenv -c TwentyFiveVoIPsBestCaseDSL -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 1 -u Cmdenv -c TwentyFiveVoIPsBestCaseDSL -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 2 -u Cmdenv -c TwentyFiveVoIPsBestCaseDSL -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 3 -u Cmdenv -c TwentyFiveVoIPsBestCaseDSL -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
fi
if [ $1 = 3 ]; then
./ex7_VoIP_full -r 0 -u Cmdenv -c TwentyFiveVoIPsWorstCaseISDN -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 1 -u Cmdenv -c TwentyFiveVoIPsWorstCaseISDN -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 2 -u Cmdenv -c TwentyFiveVoIPsWorstCaseISDN -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 3 -u Cmdenv -c TwentyFiveVoIPsWorstCaseISDN -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
fi
if [ $1 = 4 ]; then
./ex7_VoIP_full -r 0 -u Cmdenv -c TwentyFiveVoIPsWorstCaseDSL -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 1 -u Cmdenv -c TwentyFiveVoIPsWorstCaseDSL -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 2 -u Cmdenv -c TwentyFiveVoIPsWorstCaseDSL -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
./ex7_VoIP_full -r 3 -u Cmdenv -c TwentyFiveVoIPsWorstCaseDSL -n ../simulations:.:../../../inet/examples:../../../inet/src -l ../../../inet/src/inet omnetpp.ini
fi

echo "Done."
